//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepidShare.Entities.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepidShare.Entities.Resource.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string btnPrevious {
            get {
                return ResourceManager.GetString("btnPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string btnPublish {
            get {
                return ResourceManager.GetString("btnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSaveFinish {
            get {
                return ResourceManager.GetString("btnSaveFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name:.
        /// </summary>
        public static string lblApplicationName {
            get {
                return ResourceManager.GetString("lblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Role.
        /// </summary>
        public static string lblApplicationRole {
            get {
                return ResourceManager.GetString("lblApplicationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Survey Role Mapping.
        /// </summary>
        public static string lblApplicationRoleMapping {
            get {
                return ResourceManager.GetString("lblApplicationRoleMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Name.
        /// </summary>
        public static string lblAttachmentName {
            get {
                return ResourceManager.GetString("lblAttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string lblContactEmailAddress {
            get {
                return ResourceManager.GetString("lblContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblContactFirstName {
            get {
                return ResourceManager.GetString("lblContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblContactLastName {
            get {
                return ResourceManager.GetString("lblContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblContactMessage {
            get {
                return ResourceManager.GetString("lblContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaytimeContact Number.
        /// </summary>
        public static string lblDaytimeContactNumber {
            get {
                return ResourceManager.GetString("lblDaytimeContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDown Text.
        /// </summary>
        public static string lblDropDownText {
            get {
                return ResourceManager.GetString("lblDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Title.
        /// </summary>
        public static string lblGroupText {
            get {
                return ResourceManager.GetString("lblGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        public static string lblInActive {
            get {
                return ResourceManager.GetString("lblInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Telephone Number.
        /// </summary>
        public static string lblMobileTelephoneNumber {
            get {
                return ResourceManager.GetString("lblMobileTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string lblNoRecordFound {
            get {
                return ResourceManager.GetString("lblNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description.
        /// </summary>
        public static string lblServiceDescription {
            get {
                return ResourceManager.GetString("lblServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Header.
        /// </summary>
        public static string lblServiceText {
            get {
                return ResourceManager.GetString("lblServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr.No..
        /// </summary>
        public static string lblSrNo {
            get {
                return ResourceManager.GetString("lblSrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Discription.
        /// </summary>
        public static string lblStepDiscription {
            get {
                return ResourceManager.GetString("lblStepDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Name.
        /// </summary>
        public static string lblStepName {
            get {
                return ResourceManager.GetString("lblStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Name.
        /// </summary>
        public static string lblSubCategoryName {
            get {
                return ResourceManager.GetString("lblSubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblSubDescription {
            get {
                return ResourceManager.GetString("lblSubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Role.
        /// </summary>
        public static string lblSurveyRole {
            get {
                return ResourceManager.GetString("lblSurveyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Tax.
        /// </summary>
        public static string lblVatTax {
            get {
                return ResourceManager.GetString("lblVatTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lnkAdd {
            get {
                return ResourceManager.GetString("lnkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string lnkComplete {
            get {
                return ResourceManager.GetString("lnkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lnkDelete {
            get {
                return ResourceManager.GetString("lnkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lnkEdit {
            get {
                return ResourceManager.GetString("lnkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string lnkView {
            get {
                return ResourceManager.GetString("lnkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist..
        /// </summary>
        public static string msgAlreadyExist {
            get {
                return ResourceManager.GetString("msgAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit, as Survey is already published..
        /// </summary>
        public static string msgCanNotEditSurvey {
            get {
                return ResourceManager.GetString("msgCanNotEditSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while completing {0}, please try again..
        /// </summary>
        public static string msgCompleteError {
            get {
                return ResourceManager.GetString("msgCompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Completed successfully..
        /// </summary>
        public static string msgCompleteSuccess {
            get {
                return ResourceManager.GetString("msgCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while deleting {0}, please try again..
        /// </summary>
        public static string msgDeleteError {
            get {
                return ResourceManager.GetString("msgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully..
        /// </summary>
        public static string msgDeleteSuccess {
            get {
                return ResourceManager.GetString("msgDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} published successfully..
        /// </summary>
        public static string msgPublishSuccess {
            get {
                return ResourceManager.GetString("msgPublishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while saving {0}, please try again..
        /// </summary>
        public static string msgSaveError {
            get {
                return ResourceManager.GetString("msgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully..
        /// </summary>
        public static string msgSaveSuccess {
            get {
                return ResourceManager.GetString("msgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} submitted successfully..
        /// </summary>
        public static string msgSubmitSuccess {
            get {
                return ResourceManager.GetString("msgSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access this survey..
        /// </summary>
        public static string msgSurveyUnAuthorized {
            get {
                return ResourceManager.GetString("msgSurveyUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while updating {0}, please try again..
        /// </summary>
        public static string msgUpdateError {
            get {
                return ResourceManager.GetString("msgUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully..
        /// </summary>
        public static string msgUpdateSuccess {
            get {
                return ResourceManager.GetString("msgUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is required..
        /// </summary>
        public static string valApplication {
            get {
                return ResourceManager.GetString("valApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Role is required..
        /// </summary>
        public static string valApplicationRole {
            get {
                return ResourceManager.GetString("valApplicationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character not allowed..
        /// </summary>
        public static string valSpecialChar {
            get {
                return ResourceManager.GetString("valSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Role is required..
        /// </summary>
        public static string valSurveyRole {
            get {
                return ResourceManager.GetString("valSurveyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
