//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepidShare.Entities.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepidShare.Entities.Resource.DocumentResponse", typeof(DocumentResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string btnBackToList {
            get {
                return ResourceManager.GetString("btnBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Document Response.
        /// </summary>
        public static string EditDocumentResponse {
            get {
                return ResourceManager.GetString("EditDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Attempt.
        /// </summary>
        public static string lblNoOfAttempt {
            get {
                return ResourceManager.GetString("lblNoOfAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document response already started via Mobile..
        /// </summary>
        public static string msgDocumentByMobile {
            get {
                return ResourceManager.GetString("msgDocumentByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is completed..
        /// </summary>
        public static string msgDocumentCompleted {
            get {
                return ResourceManager.GetString("msgDocumentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document already expired..
        /// </summary>
        public static string msgDocumentExpired {
            get {
                return ResourceManager.GetString("msgDocumentExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is not published..
        /// </summary>
        public static string msgDocumentNotPublished {
            get {
                return ResourceManager.GetString("msgDocumentNotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document response not exist..
        /// </summary>
        public static string msgDocumentResponseNotExist {
            get {
                return ResourceManager.GetString("msgDocumentResponseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple response not allowed..
        /// </summary>
        public static string msgDocumentSingleResponse {
            get {
                return ResourceManager.GetString("msgDocumentSingleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question(s)  not available..
        /// </summary>
        public static string msgNoQuestion {
            get {
                return ResourceManager.GetString("msgNoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to response this document..
        /// </summary>
        public static string msgSaveDocumentUnauthorized {
            get {
                return ResourceManager.GetString("msgSaveDocumentUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error in {0}, please try again..
        /// </summary>
        public static string msgViewDocumentError {
            get {
                return ResourceManager.GetString("msgViewDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this document..
        /// </summary>
        public static string msgViewDocumentUnauthorized {
            get {
                return ResourceManager.GetString("msgViewDocumentUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Document Preview.
        /// </summary>
        public static string PreviewDocumentResponse {
            get {
                return ResourceManager.GetString("PreviewDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Document Response.
        /// </summary>
        public static string SaveDocumentResponse {
            get {
                return ResourceManager.GetString("SaveDocumentResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is required..
        /// </summary>
        public static string valAnswer {
            get {
                return ResourceManager.GetString("valAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} decimal place value accepted..
        /// </summary>
        public static string valDecimalPlaces {
            get {
                return ResourceManager.GetString("valDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer must be between {0} and {1}..
        /// </summary>
        public static string valNumberText {
            get {
                return ResourceManager.GetString("valNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Document Response.
        /// </summary>
        public static string ViewDocumentResponse {
            get {
                return ResourceManager.GetString("ViewDocumentResponse", resourceCulture);
            }
        }
    }
}
