//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepidShare.Entities.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepidShare.Entities.Resource.QuestionTypeResource", typeof(QuestionTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Only.
        /// </summary>
        public static string DateOnly {
            get {
                return ResourceManager.GetString("DateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of character.
        /// </summary>
        public static string MaxNumberChar {
            get {
                return ResourceManager.GetString("MaxNumberChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Decimal.
        /// </summary>
        public static string NoOfDecimal {
            get {
                return ResourceManager.GetString("NoOfDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines.
        /// </summary>
        public static string NoOfLines {
            get {
                return ResourceManager.GetString("NoOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Date.
        /// </summary>
        public static string SpecificDate {
            get {
                return ResourceManager.GetString("SpecificDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Date.
        /// </summary>
        public static string TodaysDate {
            get {
                return ResourceManager.GetString("TodaysDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Options is required..
        /// </summary>
        public static string valAnswerOptions {
            get {
                return ResourceManager.GetString("valAnswerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value is required..
        /// </summary>
        public static string valDefaultValue {
            get {
                return ResourceManager.GetString("valDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value must be greater than Min Value..
        /// </summary>
        public static string valMaxMinValue {
            get {
                return ResourceManager.GetString("valMaxMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of character is required..
        /// </summary>
        public static string valMaxNumberChar {
            get {
                return ResourceManager.GetString("valMaxNumberChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value is required..
        /// </summary>
        public static string valMaxValue {
            get {
                return ResourceManager.GetString("valMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value is required..
        /// </summary>
        public static string valMinValue {
            get {
                return ResourceManager.GetString("valMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Decimal is required..
        /// </summary>
        public static string valNoOfDecimal {
            get {
                return ResourceManager.GetString("valNoOfDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines is required..
        /// </summary>
        public static string valNoOfLines {
            get {
                return ResourceManager.GetString("valNoOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of character must be between 1 and 500..
        /// </summary>
        public static string valRanageMaxNumberChar {
            get {
                return ResourceManager.GetString("valRanageMaxNumberChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Decimal must be between 0 and 3..
        /// </summary>
        public static string valRanageNoOfDecimal {
            get {
                return ResourceManager.GetString("valRanageNoOfDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines must be between 1 and 20..
        /// </summary>
        public static string valRanageNoOfLine {
            get {
                return ResourceManager.GetString("valRanageNoOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Specific Date..
        /// </summary>
        public static string valSpecificDate {
            get {
                return ResourceManager.GetString("valSpecificDate", resourceCulture);
            }
        }
    }
}
